name: Release Branch Update

on: [release]

permissions:
  contents: write

jobs:
  update-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      
      - name: Prepare a Blank Release Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout --orphan release
          git rm -rf .
          git clean -fd  

      - name: Prepare ZIP
        # Fetch the latest release ZIP, extract, remove versiontage from folder structure, and re-zip it
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          ZIP_URL=$(curl -s https://api.github.com/repos/DroneML/CoeusAI/releases/latest | jq -r '.zipball_url')
          DOWNLOAD_ZIP="CoeusAI-${RELEASE_TAG}.zip"
          curl -L -o ${DOWNLOAD_ZIP} -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${ZIP_URL}
          unzip ${DOWNLOAD_ZIP} -d extracted_files
          ls -l extracted_files
          ORIGINAL_FOLDER=$(ls extracted_files)
          mv extracted_files/${ORIGINAL_FOLDER} extracted_files/CoeusAI
          ls -l extracted_files
          mv extracted_files/CoeusAI .
          ls -l .
          ls -l CoeusAI
          zip -r CoeusAI.zip CoeusAI

      - name: Commit and Push the zip file
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add CoeusAI.zip
          git commit -m "Add latest release ZIP with renamed folder structure"
          git push origin release --force
