name: Release Branch Update

on:
  pull_request:
    branches:
    - main

jobs:
  update-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Release ZIP
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          ZIP_URL=$(curl -s https://api.github.com/repos/DroneML/DroneML/releases/latest | jq -r '.zipball_url')
          DOWNLOAD_ZIP="DroneML-${RELEASE_TAG}.zip"
          curl -L -o ${DOWNLOAD_ZIP} -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" ${ZIP_URL}
          unzip ${DOWNLOAD_ZIP} -d extracted_files
          ls -l extracted_files
          ORIGINAL_FOLDER=$(ls extracted_files)
          mv extracted_files/${ORIGINAL_FOLDER} extracted_files/DroneML
          ls -l extracted_files
          mkdir -p DroneML
          mv extracted_files/DroneML DroneML
          ls -l .
          ls -l DroneML
          zip -r DroneML.zip DroneML
          git checkout --orphan release
          git add DroneML.zip
          git commit -m "Add latest release ZIP with renamed folder structure"
          git push origin release --force