name: Release Branch Update

on:
  pull_request:
    branches:
    - main

jobs:
  update-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensure we can manipulate branches

      - name: Download Release ZIP
        run: |
          RELEASE_TAG=$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r '.tag_name')
          ZIP_URL=$(curl -s https://api.github.com/repos/DroneML/DroneML/releases/latest | jq -r '.zipball_url')
          DOWNLOAD_ZIP=$(DroneML "${RELEASE_TAG}" .zip)
          echo "RELEASE_TAG=${RELEASE_TAG}" >> $GITHUB_ENV
          echo "ZIP_URL=${ZIP_URL}" >> $GITHUB_ENV
          echo "DOWNLOAD_ZIP=${DOWNLOAD_ZIP}" >> $GITHUB_ENV
          curl -L -o "${{env.DOWNLOAD_ZIP}}" -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "${{ env.ZIP_URL }}"

      - name: Rename Folder Structure
        run: |
          unzip "${{ env.DOWNLOAD_ZIP }}.zip" -d extracted_files
          ls -l extracted_files
          ORIGINAL_FOLDER=$(ls extracted_files)
          mv "extracted_files/$ORIGINAL_FOLDER" "extracted_files/release"
          mkdir -p release
          mv extracted_files/release release
          zip -r release.zip release
          ls -l

      - name: Update `release` Branch
        run: |
          git checkout --orphan release
          git clean -fd
          git add release.zip
          git commit -m "Add latest release ZIP with renamed folder structure"
          git push origin release --force